In [3]:
import pandas as pd

# replace with your file path
df = pd.read_csv("distance_df_kai.csv")

In [4]:
df_tirz_gip = df[df.dock == "tirz_GIP_7BRT"]
df_tirz_gip[df_tirz_gip.distance < 4][["atom2_residue", "atom2_residue_num"]].drop_duplicates().sort_values("atom2_residue_num").reset_index(drop=True)

   atom2_residue  atom2_residue_num
0            TYR                  1
1            ALA                  2
2            GLU                  3
3            GLY                  4
4            THR                  5
5            PHE                  6
6            THR                  7
7            SER                  8
8            ASP                  9
9            TYR                 10
10           SER                 11
11           ILE                 12
12           LEU                 14
13           ASP                 15
14           LYS                 16
15           ILE                 17
16           ALA                 18
17           GLN                 19
18           LYS                 20
19           PHE                 22
20           VAL                 23
21           LEU                 26
22           ILE                 27
23           GLY                 30

In [5]:
df_tirz_glp1 = df[df.dock == "tirz_GLP_6XOX"]
df_tirz_glp1[df_tirz_glp1.distance < 4][["atom2_residue", "atom2_residue_num"]].drop_duplicates().sort_values("atom2_residue_num").reset_index(drop=True)

   atom2_residue  atom2_residue_num
0            TYR                  1
1            ALA                  2
2            GLU                  3
3            THR                  5
4            PHE                  6
5            THR                  7
6            SER                  8
7            ASP                  9
8            TYR                 10
9            SER                 11
10           ILE                 12
11           ALA                 13
12           LEU                 14
13           ASP                 15
14           LYS                 16
15           ILE                 17
16           ALA                 18
17           GLN                 19
18           LYS                 20
19           ALA                 21
20           PHE                 22
21           VAL                 23
22           TRP                 25
23           LEU                 26
24           ILE                 27
25           ALA                 28
26           PRO                 31
27           SER                 32
28           SER                 33
29           GLY                 34
30           ALA                 35
31           PRO                 36
32           PRO                 38

In [7]:
df_kai_gip = df[df.dock == "kai_GIP_7BRT"]
df_kai_gip[df_kai_gip.distance < 4][["atom2_residue", "atom2_residue_num"]].drop_duplicates().sort_values("atom2_residue_num").reset_index(drop=True)

   atom2_residue  atom2_residue_num
0            TYR                  1
1            ALA                  2
2            GLU                  3
3            GLY                  4
4            THR                  5
5            PHE                  6
6            THR                  7
7            SER                  8
8            ASP                  9
9            TYR                 10
10           SER                 11
11           ILE                 12
12           TYR                 13
13           LYS                 14
14           GLU                 15
15           ARG                 16
16           ILE                 17
17           ALA                 18
18           ALA                 19
19           GLN                 20
20           GLU                 21
21           PHE                 22
22           VAL                 23
23           ASN                 24
24           TRP                 25
25           LEU                 26
26           LEU                 27
27           GLY                 29
28           GLY                 30
29           PRO                 31
30           SER                 32
31           SER                 33
32           GLY                 34
33           ALA                 35

In [8]:
df_kai_glp = df[df.dock == "tirz_GLP_6XOX"]
df_kai_glp[df_kai_glp.distance < 4][["atom2_residue", "atom2_residue_num"]].drop_duplicates().sort_values("atom2_residue_num").reset_index(drop=True)

   atom2_residue  atom2_residue_num
0            TYR                  1
1            ALA                  2
2            GLU                  3
3            THR                  5
4            PHE                  6
5            THR                  7
6            SER                  8
7            ASP                  9
8            TYR                 10
9            SER                 11
10           ILE                 12
11           ALA                 13
12           LEU                 14
13           ASP                 15
14           LYS                 16
15           ILE                 17
16           ALA                 18
17           GLN                 19
18           LYS                 20
19           ALA                 21
20           PHE                 22
21           VAL                 23
22           TRP                 25
23           LEU                 26
24           ILE                 27
25           ALA                 28
26           PRO                 31
27           SER                 32
28           SER                 33
29           GLY                 34
30           ALA                 35
31           PRO                 36
32           PRO                 38